[package]
name = "cef"
version = "0.1.0"
authors = ["Andreas Monitzer <andreas@monitzer.com>", "Osspial <osspial@gmail.com>"]
edition = "2018"

[dependencies]
cef-sys = { git = "https://github.com/anlumo/cef-sys.git" }
num_enum = "0.4"
parking_lot = "0.9"
downcast-rs = "1.1"
libc = "0.2"
bitflags = "1"
lazy_static = "1"
chashmap = "2"
raw-window-handle = "0.3"

[dev-dependencies]
winit = "=0.20.0-alpha4"
# winit-blit = {git = "https://github.com/rust-windowing/winit-blit.git"}

# I'm temporarily pulling in my opengl wrapper because it's
# 12:30 AM and I don't want to learn wgpu right now.
gullery = {git = "https://github.com/Osspial/gullery.git" }
gullery_macros = {git = "https://github.com/Osspial/gullery.git" }
glutin = "0.22.0-alpha3"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3" }

[target.'cfg(windows)'.dev-dependencies]
winapi = { version = "0.3", features = ["winuser", "libloaderapi"] }
